{"label": "TP", "vulnerability_id": "CVE-2020-26116", "source": "manual", "note": "", "category": null, "user": "samdacanay", "image": {"exact": "docker.io/cloudbees/cloudbees-core-mm@sha256:4c564f473d38f23da1caa48c4ef53b958ef03d279232007ad3319b1f38584bdb", "regex": null, "prefix": null, "suffix": null}, "package": {"name": "platform-python", "version": "3.6.8-31.el8"}, "fullentry_fields": [], "timestamp": "2022-09-06T21:59:51-04:00", "ID": "14ef8018-d9ff-47a5-bdbf-af17d4cd385a"}